// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/9/2024, 1:14:06 PM
const configMerger = require("/Users/jamievidamour/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/jamievidamour/Documents/Dev/TPSched/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jamievidamour/Documents/Dev/TPSched/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jamievidamour/Documents/Dev/TPSched/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jamievidamour/Documents/Dev/TPSched/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jamievidamour/Documents/Dev/TPSched/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jamievidamour/Documents/Dev/TPSched/plugins/**/*.{js,ts,mjs}","/Users/jamievidamour/Documents/Dev/TPSched/composables/**/*.{js,ts,mjs}","/Users/jamievidamour/Documents/Dev/TPSched/utils/**/*.{js,ts,mjs}","/Users/jamievidamour/Documents/Dev/TPSched/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/jamievidamour/Documents/Dev/TPSched/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/jamievidamour/Documents/Dev/TPSched/app.config.{js,ts,mjs}"] }));

module.exports = config 
